"""add shadowing review jobs

Revision ID: c0350900f515
Revises: a1b2c3d4e5f6
Create Date: 2026-09-06 15:34:43.153422
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c0350900f515"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "shadowing_worker_heartbeats",
        sa.Column("worker_id", sa.Uuid(), nullable=False),
        sa.Column(
            "heartbeat_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("worker_id"),
    )
    op.create_index(
        "ix_shadowing_worker_heartbeats_heartbeat_at",
        "shadowing_worker_heartbeats",
        ["heartbeat_at"],
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shadowing_attempt_segments",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("segment_index", sa.Integer(), nullable=False),
        sa.Column("script", sa.Text(), nullable=False),
        sa.Column("start_time_ms", sa.Integer(), nullable=False),
        sa.Column("end_time_ms", sa.Integer(), nullable=False),
        sa.Column("recording_id", sa.Uuid(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "completion_eligible", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "transcription_status",
            sa.String(length=24),
            server_default="not_recorded",
            nullable=False,
        ),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("comparison", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "transcription_status IN ('not_recorded', 'not_requested', 'queued', 'processing', "
            "'completed', 'no_speech', 'failed', 'unavailable', 'not_evaluable')",
            name="shadowing_segment_transcription_status",
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0", name="shadowing_segment_duration_nonnegative"
        ),
        sa.CheckConstraint("length(trim(script)) > 0", name="shadowing_segment_script_nonempty"),
        sa.CheckConstraint("segment_index >= 0", name="shadowing_segment_index_nonnegative"),
        sa.CheckConstraint(
            "start_time_ms >= 0 AND end_time_ms > start_time_ms",
            name="shadowing_segment_timing_valid",
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["exercise_attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recording_id"], ["recordings.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", "segment_index", name="uq_shadowing_attempt_segment"),
    )
    op.create_table(
        "shadowing_jobs",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("recording_id", sa.Uuid(), nullable=True),
        sa.Column("evaluation_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("batch_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="queued", nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('transcribe_recording', 'evaluate_batch', 'summarize_feedback')",
            name="shadowing_job_kind",
        ),
        sa.CheckConstraint(
            "status != 'processing' OR (lease_token IS NOT NULL AND locked_until IS NOT NULL)",
            name="shadowing_job_processing_lease",
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'processing', 'completed', 'failed')", name="shadowing_job_status"
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND max_attempts >= 1 AND batch_index >= 0",
            name="shadowing_job_counts_valid",
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["exercise_attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evaluation_id"], ["ai_evaluations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recording_id"], ["recordings.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "attempt_id", "kind", "input_fingerprint", "batch_index", name="uq_shadowing_job_input"
        ),
    )
    op.create_index(
        "ix_shadowing_jobs_claim",
        "shadowing_jobs",
        ["kind", "status", "available_at", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_shadowing_jobs_expired",
        "shadowing_jobs",
        ["locked_until"],
        unique=False,
        postgresql_where=sa.text("status = 'processing'"),
    )
    op.add_column(
        "ai_evaluations", sa.Column("review_fingerprint", sa.String(length=64), nullable=True)
    )
    op.create_unique_constraint(
        "uq_ai_evaluations_review_fingerprint",
        "ai_evaluations",
        ["attempt_id", "review_fingerprint"],
    )
    op.add_column(
        "exercise_attempts",
        sa.Column("review_revision", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("recordings", sa.Column("client_recording_id", sa.Uuid(), nullable=True))
    op.add_column("recordings", sa.Column("content_sha256", sa.String(length=64), nullable=True))
    op.add_column("recordings", sa.Column("shadowing_segment_index", sa.Integer(), nullable=True))
    op.create_unique_constraint(
        "uq_recordings_client_take", "recordings", ["user_id", "attempt_id", "client_recording_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        "ix_shadowing_worker_heartbeats_heartbeat_at", table_name="shadowing_worker_heartbeats"
    )
    op.drop_table("shadowing_worker_heartbeats")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_recordings_client_take", "recordings", type_="unique")
    op.drop_column("recordings", "content_sha256")
    op.drop_column("recordings", "shadowing_segment_index")
    op.drop_column("recordings", "client_recording_id")
    op.drop_column("exercise_attempts", "review_revision")
    op.drop_constraint("uq_ai_evaluations_review_fingerprint", "ai_evaluations", type_="unique")
    op.drop_column("ai_evaluations", "review_fingerprint")
    op.drop_index(
        "ix_shadowing_jobs_expired",
        table_name="shadowing_jobs",
        postgresql_where=sa.text("status = 'processing'"),
    )
    op.drop_index("ix_shadowing_jobs_claim", table_name="shadowing_jobs")
    op.drop_table("shadowing_jobs")
    op.drop_table("shadowing_attempt_segments")
    # ### end Alembic commands ###
