# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [dev,master]

jobs:
  backend:
    name: Backend (lint, format, type-check, test)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    env:
      DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Lint (ruff)
        run: uv run ruff check .

      - name: Format check (ruff)
        run: uv run ruff format --check .

      - name: Type check (mypy)
        run: uv run mypy

      - name: Run migration on Neon test branch
        run: DATABASE_URL=$DATABASE_URL_TEST uv run alembic upgrade head

      #- name: Run tests
      #  run: uv run pytest

  frontend:
    name: Frontend (lint, typecheck, format)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint:web

      #- name: Type check
      #  run: pnpm --filter web typecheck

      - name: Format check (prettier)
        run: pnpm format:check
